### ISSUE TITLE
Unable to run: error events.js:141

### ISSUE THREAD

**Issue by danethomas** [angusfretwell/generator-craftsman#35]
Was keen to use this as we're also using Craft and Dokku. Seem to be running into an issue when running ``yo craftsman``

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: You must provide a `message` parameter
    at Prompt.throwParamError (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:88:9)
    at Prompt (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:44:10)
    at new Prompt (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/input.js:25:15)
    at PromptUI.fetchAnswer (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:92:16)
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:4599:20
    at tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:4806:43)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
```

I've tried to update some of the versions in package.json and have also manually added ``babel eslint babel-eslint`` to the ``npm install -g `` list. 

Any ideas?

**Comment by angusfretwell** [comment]
Hey,

This was solved in 9d8ba3faa1de0e84c357eba1df549b3506210a3d. 

Thanks for your interest in Craftsman; there's quite bit of work I want to do on it, so I'd be interested in your thoughts on the changes/features I've proposed in the [other issues](https://github.com/angusfretwell/generator-craftsman/issues). Hopefully the idea of Craftsman solving a problem for someone other than myself will inspire me to get some work done on it :smile:
